#!/bin/sh
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0
# reset field values
cp -r 0.org 0
# remove old graphic files
rm  log* Dt.dat Pc.agr kr.agr 
